import Redis from 'ioredis';
import * as sequelize from 'sequelize';
import { Sequelize } from 'sequelize';
import * as typeorm from 'typeorm';
import * as Waterline from 'waterline';
import { IOrmMwConfig, IOrmsOut, RequestHandler } from './interfaces.d';
export declare const tearDownRedisConnection: (connection: Redis.Redis, done: (error?: any) => any) => any;
export declare const tearDownSequelizeConnection: (connection: sequelize.Sequelize, done: (error?: any) => any) => any;
export declare const tearDownTypeOrmConnection: (connection: typeorm.Connection, done: (error?: any) => any) => any;
export declare const tearDownWaterlineConnection: (connections: Waterline.Connection[], done: (error?: any) => any) => any;
export declare const tearDownConnections: (orms: IOrmsOut, done: (error?: any) => any) => any;
export declare const ormMw: (options: IOrmMwConfig) => RequestHandler | void;
