import Redis from 'ioredis';
import sequelize, { Sequelize } from 'sequelize';
import { Connection as TypeOrmConnection } from 'typeorm';
import { Connection as WaterlineConnection } from 'waterline';
import { IOrmMwConfig, IOrmsOut, RequestHandler } from './interfaces.d';
export declare const tearDownRedisConnection: (connection: Redis.Redis, done: (error?: any) => any) => any;
export declare const tearDownSequelizeConnection: (connection: sequelize.Sequelize, done: (error?: any) => any) => any;
export declare const tearDownTypeOrmConnection: (connection: TypeOrmConnection, done: (error?: any) => any) => any;
export declare const tearDownWaterlineConnection: (connections: WaterlineConnection[], done: (error?: any) => any) => any;
export declare const tearDownConnections: (orms: IOrmsOut, done: (error?: any) => any) => any;
export declare const ormMw: (options: IOrmMwConfig) => RequestHandler | void;
